/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef WINUPDATER_PRIVATE_H
#define WINUPDATER_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"2.0.0.0"
#define VER_MAJOR	2
#define VER_MINOR	0
#define VER_RELEASE	0
#define VER_BUILD	0
#define COMPANY_NAME	""
#define FILE_VERSION	"2.0.0.0"
#define FILE_DESCRIPTION	"WinUpdater"
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	"Marian Dolinský"
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	""
#define PRODUCT_NAME	"WinUpdater"
#define PRODUCT_VERSION	"2.0.0.0"

#endif /*WINUPDATER_PRIVATE_H*/
