//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoOZapujceni
    {
        public int Id { get; set; }
        public int KnihovnaID { get; set; }
        public int SkolaZaciID { get; set; }
        public System.DateTime DatumZapujceni { get; set; }
        public Nullable<System.DateTime> DatumVraceni { get; set; }
    
        public virtual Knihovna Knihovna { get; set; }
        public virtual SkolaZaci SkolaZaci { get; set; }
    }
}
