//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Knihovna
    {
        public int Id { get; set; }
        public string Nazev { get; set; }
        public Nullable<int> ZapujcenoID { get; set; }
        public string Autor { get; set; }
    
        public virtual SkolaZaci SkolaZaci { get; set; }
    }
}
