//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SkolaZaci
    {
        public int Id { get; set; }
        public string Jmeno { get; set; }
        public string Prijmeni { get; set; }
        public string RodneCislo { get; set; }
        public Nullable<bool> JeMuz { get; set; }
        public string Trida { get; set; }
        public Nullable<bool> Studuje { get; set; }
        public System.DateTime DatumZmeny { get; set; }
        public string AutorZmeny { get; set; }
    }
}
